const RELEASEN_CRON_PATTERN = process.env.RELEASEN_CRON_PATTERN || '0 * * * * *';
const ESTIMATED_DURATION = process.env.ESTIMATED_DURATION || 5;

export {
  RELEASEN_CRON_PATTERN,
  ESTIMATED_DURATION
}