const RELEASE_CRON_PATTERN = process.env.RELEASE_CRON_PATTERN || '0 * * * * *';
const ESTIMATED_DURATION = parseInt(process.env.ESTIMATED_DURATION || '600') * 1000;

export {
  RELEASE_CRON_PATTERN,
  ESTIMATED_DURATION
}
